# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20161006_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
