# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_auto_20161007_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
