# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_show_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
