# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_auto_20161007_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='movie_db_id',
            field=models.IntegerField(default=1),
        ),
    ]
