# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_auto_20161007_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='movie_db_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
