# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_auto_20161007_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='popularity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='popularity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='popularity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
