# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_auto_20161007_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='season',
            name='popularity',
        ),
    ]
