# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_auto_20161007_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='air_date',
            field=models.DateField(auto_now=True),
        ),
    ]
