# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0012_episode_air_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateField(),
        ),
    ]
