# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0013_auto_20161010_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
