# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0014_auto_20161010_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
