# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0015_show_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='episode_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
