# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0016_show_episode_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='first_air',
            field=models.DateField(blank=True, null=True),
        ),
    ]
