# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0017_show_first_air'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='local_img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='server_img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='vote_average',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='vote_count',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
