# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0018_auto_20161012_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='local_img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='server_img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='local_img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='server_img_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
